### ISSUE TITLE
Cannot compute dep graph

### ISSUE THREAD

**Issue by Suyashtnt** [nxrs/cargo#11] opened 2022-02-18 09:47 UTC
rt
![image](https://user-images.githubusercontent.com/45307955/154658333-b28a7f09-cacf-4253-b6a5-4cdf488b25f6.png)

output of verbose mode:
```
glowsquid on  dev via  v16.14.0 via 🦀 v1.58.1 took 3s
❯ NX_VERBOSE_LOGGING=true yarn build oxidize
<ref *1> Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:814:24)
    at Object.execSync (node:child_process:897:15)
    at Object.processProjectGraph (/run/media/tntman/BulkStorage/projects/glowsquid/node_modules/@nxrs/cargo/src/graph/index.js:9:23)
    at /run/media/tntman/BulkStorage/projects/glowsquid/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:215:27
    at Array.reduce (<anonymous>)
    at updateProjectGraphWithPlugins (/run/media/tntman/BulkStorage/projects/glowsquid/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:213:28)
    at /run/media/tntman/BulkStorage/projects/glowsquid/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:87:19
    at Generator.next (<anonymous>)
    at fulfilled (/run/media/tntman/BulkStorage/projects/glowsquid/node_modules/tslib/tslib.js:114:62) {
  errno: -105,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [ '-c', 'cargo metadata --format-version=1' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    '{"packages":[{"name":"adler","version":"1.0.2","id":"adler 1.0.2 (registry+https://github.com/rust-lang/crates.io-index)","license":"0BSD OR MIT OR Apache-2.0","license_file":null,"description":"A simple clean-room implementation of the Adler-32 checksum","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"compiler_builtins","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.1.2","kind":null,"rename":null,"optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"rustc-std-workspace-core","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.0","kind":null,"rename":"core","optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"criterion","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3.2","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"adler","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/src/lib.rs","edition":"2015","doc":true,"doctest":true,"test":true},{"kind":["bench"],"crate_types":["bin"],"name":"bench","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/benches/bench.rs","edition":"2015","doc":false,"doctest":false,"test":false}],"features":{"default":["std"],"rustc-dep-of-std":["core","compiler_builtins"],"std":[]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/Cargo.toml","metadata":{"docs":{"rs":{"rustdoc-args":["--cfg=docsrs"]}},"release":{"no-dev-version":true,"pre-release-commit-message":"Release {{version}}","tag-message":"{{version}}","pre-release-replacements":[{"file":"CHANGELOG.md","replace":"## Unreleased\\n\\nNo changes.\\n\\n## [{{version}} - {{date}}](https://github.com/jonas-schievink/adler/releases/tag/v{{version}})\\n","search":"## Unreleased\\n"},{"file":"README.md","replace":"adler = \\"{{version}}\\"","search":"adler = \\"[a-z0-9\\\\\\\\.-]+\\""},{"file":"src/lib.rs","replace":"https://docs.rs/adler/{{version}}","search":"https://docs.rs/adler/[a-z0-9\\\\.-]+"}]}},"publish":null,"authors":["Jonas Schievink <jonasschievink@gmail.com>"],"categories":["algorithms"],"keywords":["checksum","integrity","hash","adler32","zlib"],"readme":"README.md","repository":"https://github.com/jonas-schievink/adler.git","homepage":null,"documentation":"https://docs.rs/adler/","edition":"2015","links":null,"default_run":null,"rust_version":null},{"name":"adler32","version":"1.2.0","id":"adler32 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)","license":"Zlib","license_file":null,"description":"Minimal Adler32 implementation for Rust.","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"compiler_builtins","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.1.2","kind":null,"rename":null,"optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"rustc-std-workspace-core","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.0","kind":null,"rename":"core","optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"criterion","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"getrandom","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.1","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":["wasm-bindgen"],"target":null,"registry":null},{"name":"humansize","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.1","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"rand","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.7","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"wasm-bindgen","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.2.63","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":"cfg(target_arch = \\"wasm32\\")","registry":null},{"name":"wasm-bindgen-test","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":"cfg(target_arch = \\"wasm32\\")","registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"adler32","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},{"kind":["bench"],"crate_types":["bin"],"name":"bench","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/src/bench.rs","edition":"2018","doc":false,"doctest":false,"test":false}],"features":{"default":["std"],"rustc-dep-of-std":["core","compiler_builtins"],"std":[]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/Cargo.toml","metadata":null,"publish":null,"authors":["Remi Rampin <remirampin@gmail.com>"],"categories":[],"keywords":["adler32","hash","rolling"],"readme":"README.md","repository":"https://github.com/remram44/adler32-rs","homepage":null,"documentation":"https://docs.rs/adler32/","edition":"2018","links":null,"default_run":null,"rust_version":null},{"name":"aho-corasick","version":"0.7.18","id":"aho-corasick 0.7.18 (registry+https://github.com/rust-lang/crates.io-index)","license":"Unlicense/MIT","license_file":null,"description":"Fast multiple substring searching.","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"memchr","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^2.4.0","kind":null,"rename":null,"optional":false,"uses_default_features":false,"features":[],"target":null,"registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"aho_corasick","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.18/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true}],"features":{"default":["std"],"std":["memchr/std"]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.18/Cargo.toml","metadata":null,"publish":null,"authors":["Andrew Gallant <jamslam@gmail.com>"],"categories":["text-processing"],"keywords":["string","search","text","aho","multi"],"readme":"README.md","repository":"https://github.com/BurntSushi/aho-corasick","homepage":"https://github.com/BurntSushi/aho-corasick","documentation":null,"edition":"2018","links":null,"default_run":null,"rust_version":null},{"name":"ansi_term","version":"0.12.1","id":"ansi_term 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)","license":"MIT","license_file":null,"description":"Library for ANSI terminal colours and styles (bold, underline)","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"serde","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.90","kind":null,"rename":null,"optional":true,"uses_default_features":true,"features":["derive"],"target":null,"registry":null},{"name":"doc-comment","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"regex","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.1.9","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"serde_json","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.39","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"winapi","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3.4","kind":null,"rename":null,"optional":false,"uses_default_features":true,"features":["consoleapi","errhandlingapi","fileapi","handleapi","processenv"],"target":"cfg(target_os = \\"windows\\")","registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"ansi_term","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/src/lib.rs","edition":"2015","doc":true,"doctest":true,"test":true},{"kind":["example"],"crate_types":["bin"],"name":"basic_colours","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/examples/basic_colours.rs","edition":"2015","doc":false,"doctest":false,"test":false},{"kind":["example"],"crate_types":["bin"],"name":"rgb_colours","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/examples/rgb_colours.rs","edition":"2015","doc":false,"doctest":false,"test":false},{"kind":["example"],"crate_types":["bin"],"name":"256_colours","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/examples/256_colours.rs","edition":"2015","doc":false,"doctest":false,"test":false}],"features":{"derive_serde_style":["serde"]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/Cargo.toml","metadata":null,"publish":null,"authors":["ogham@bsago.me","Ryan Scheel (Havvy) <ryan.havvy@gmail.com>","Josh Triplett <josh@joshtriplett.org>"],"categories":[],"keywords":[],"readme":"README.md","repository":"https://github.com/ogham/rust-ansi-term","homepage":"https://github.com/ogham/rust-ansi-term","documentation":"https://docs.rs/ansi_term","edition":"2015","links":null,"default_run":null,"rust_versi'... 1104070 more characters,
    ''
  ],
  pid: 122805,
  stdout: '{"packages":[{"name":"adler","version":"1.0.2","id":"adler 1.0.2 (registry+https://github.com/rust-lang/crates.io-index)","license":"0BSD OR MIT OR Apache-2.0","license_file":null,"description":"A simple clean-room implementation of the Adler-32 checksum","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"compiler_builtins","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.1.2","kind":null,"rename":null,"optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"rustc-std-workspace-core","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.0","kind":null,"rename":"core","optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"criterion","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3.2","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"adler","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/src/lib.rs","edition":"2015","doc":true,"doctest":true,"test":true},{"kind":["bench"],"crate_types":["bin"],"name":"bench","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/benches/bench.rs","edition":"2015","doc":false,"doctest":false,"test":false}],"features":{"default":["std"],"rustc-dep-of-std":["core","compiler_builtins"],"std":[]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/Cargo.toml","metadata":{"docs":{"rs":{"rustdoc-args":["--cfg=docsrs"]}},"release":{"no-dev-version":true,"pre-release-commit-message":"Release {{version}}","tag-message":"{{version}}","pre-release-replacements":[{"file":"CHANGELOG.md","replace":"## Unreleased\\n\\nNo changes.\\n\\n## [{{version}} - {{date}}](https://github.com/jonas-schievink/adler/releases/tag/v{{version}})\\n","search":"## Unreleased\\n"},{"file":"README.md","replace":"adler = \\"{{version}}\\"","search":"adler = \\"[a-z0-9\\\\\\\\.-]+\\""},{"file":"src/lib.rs","replace":"https://docs.rs/adler/{{version}}","search":"https://docs.rs/adler/[a-z0-9\\\\.-]+"}]}},"publish":null,"authors":["Jonas Schievink <jonasschievink@gmail.com>"],"categories":["algorithms"],"keywords":["checksum","integrity","hash","adler32","zlib"],"readme":"README.md","repository":"https://github.com/jonas-schievink/adler.git","homepage":null,"documentation":"https://docs.rs/adler/","edition":"2015","links":null,"default_run":null,"rust_version":null},{"name":"adler32","version":"1.2.0","id":"adler32 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)","license":"Zlib","license_file":null,"description":"Minimal Adler32 implementation for Rust.","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"compiler_builtins","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.1.2","kind":null,"rename":null,"optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"rustc-std-workspace-core","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.0","kind":null,"rename":"core","optional":true,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"criterion","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"getrandom","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.1","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":["wasm-bindgen"],"target":null,"registry":null},{"name":"humansize","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.1","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"rand","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.7","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"wasm-bindgen","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.2.63","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":"cfg(target_arch = \\"wasm32\\")","registry":null},{"name":"wasm-bindgen-test","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":"cfg(target_arch = \\"wasm32\\")","registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"adler32","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},{"kind":["bench"],"crate_types":["bin"],"name":"bench","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/src/bench.rs","edition":"2018","doc":false,"doctest":false,"test":false}],"features":{"default":["std"],"rustc-dep-of-std":["core","compiler_builtins"],"std":[]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/Cargo.toml","metadata":null,"publish":null,"authors":["Remi Rampin <remirampin@gmail.com>"],"categories":[],"keywords":["adler32","hash","rolling"],"readme":"README.md","repository":"https://github.com/remram44/adler32-rs","homepage":null,"documentation":"https://docs.rs/adler32/","edition":"2018","links":null,"default_run":null,"rust_version":null},{"name":"aho-corasick","version":"0.7.18","id":"aho-corasick 0.7.18 (registry+https://github.com/rust-lang/crates.io-index)","license":"Unlicense/MIT","license_file":null,"description":"Fast multiple substring searching.","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"memchr","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^2.4.0","kind":null,"rename":null,"optional":false,"uses_default_features":false,"features":[],"target":null,"registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"aho_corasick","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.18/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true}],"features":{"default":["std"],"std":["memchr/std"]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.18/Cargo.toml","metadata":null,"publish":null,"authors":["Andrew Gallant <jamslam@gmail.com>"],"categories":["text-processing"],"keywords":["string","search","text","aho","multi"],"readme":"README.md","repository":"https://github.com/BurntSushi/aho-corasick","homepage":"https://github.com/BurntSushi/aho-corasick","documentation":null,"edition":"2018","links":null,"default_run":null,"rust_version":null},{"name":"ansi_term","version":"0.12.1","id":"ansi_term 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)","license":"MIT","license_file":null,"description":"Library for ANSI terminal colours and styles (bold, underline)","source":"registry+https://github.com/rust-lang/crates.io-index","dependencies":[{"name":"serde","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.90","kind":null,"rename":null,"optional":true,"uses_default_features":true,"features":["derive"],"target":null,"registry":null},{"name":"doc-comment","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"regex","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.1.9","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"serde_json","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.39","kind":"dev","rename":null,"optional":false,"uses_default_features":true,"features":[],"target":null,"registry":null},{"name":"winapi","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3.4","kind":null,"rename":null,"optional":false,"uses_default_features":true,"features":["consoleapi","errhandlingapi","fileapi","handleapi","processenv"],"target":"cfg(target_os = \\"windows\\")","registry":null}],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"ansi_term","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/src/lib.rs","edition":"2015","doc":true,"doctest":true,"test":true},{"kind":["example"],"crate_types":["bin"],"name":"basic_colours","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/examples/basic_colours.rs","edition":"2015","doc":false,"doctest":false,"test":false},{"kind":["example"],"crate_types":["bin"],"name":"rgb_colours","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/examples/rgb_colours.rs","edition":"2015","doc":false,"doctest":false,"test":false},{"kind":["example"],"crate_types":["bin"],"name":"256_colours","src_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/examples/256_colours.rs","edition":"2015","doc":false,"doctest":false,"test":false}],"features":{"derive_serde_style":["serde"]},"manifest_path":"/home/tntman/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.12.1/Cargo.toml","metadata":null,"publish":null,"authors":["ogham@bsago.me","Ryan Scheel (Havvy) <ryan.havvy@gmail.com>","Josh Triplett <josh@joshtriplett.org>"],"categories":[],"keywords":[],"readme":"README.md","repository":"https://github.com/ogham/rust-ansi-term","homepage":"https://github.com/ogham/rust-ansi-term","documentation":"https://docs.rs/ansi_term","edition":"2015","links":null,"default_run":null,"rust_versi'... 1104070 more characters,
  stderr: ''
}
Failed to process the project graph with "@nxrs/cargo". This will error in the future!

 >  NX   RunStart


{
  "meta": {
    "nxCloudVersion": "latest"
  },
  "branch": null,
  "runGroup": "258503086da7a63149fca8bbd17472907d266c57",
  "hashes": []
}


 >  NX   RunStart


{
  "meta": {
    "nxCloudVersion": "latest"
  },
  "branch": null,
  "runGroup": "258503086da7a63149fca8bbd17472907d266c57",
  "hashes": [
    "c5e7f2e74d0a942f665df4e3c6eb78ec047bcd3d3b2dd8e1741e5d1f86a4fa44"
  ]
}


 >  NX   Nx Cloud: Cache miss c5e7f2e74d0a942f665df4e3c6eb78ec047bcd3d3b2dd8e1741e5d1f86a4fa44.


> nx run oxidize:build

> cargo +nightly build --bin oxidize --target-dir ../../dist/apps/oxide/target -Z unstable-options --out-dir ../../dist/apps/oxide/builds/debug
error: no bin target named `oxidize`

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project oxidize (2s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]


 >  NX   RunEnd. Completed tasks


[
  {
    "taskId": "oxidize:build",
    "startTime": "2022-02-18T09:47:11.218Z",
    "target": "build",
    "projectName": "oxidize",
    "hash": "c5e7f2e74d0a942f665df4e3c6eb78ec047bcd3d3b2dd8e1741e5d1f86a4fa44",
    "hashDetails": {
      "nodes": {
        "oxidize": "fd0153c875e149eb9a76c99a5bf923d2d2b58a4b20fe0c73dd9aedd5e6363e5e"
      },
      "runtime": {},
      "implicitDeps": {
        "/run/media/tntman/BulkStorage/projects/glowsquid/package.json": "63edd6fa919cf231a47d20367fe1126a19916668a0d8f1d88d0ea6c6c62f4bf1",
        "/run/media/tntman/BulkStorage/projects/glowsquid/.eslintrc.json": "ce764c60ea27b190bfc7c5a49d94aaa869f715ccf48d17f5d181a3ba702e09db",
        "/run/media/tntman/BulkStorage/projects/glowsquid/yarn.lock": "ce672bf1212f09a5de3725b75e0667cca7f1dd681d8efdefb8d882841488f86e",
        "/run/media/tntman/BulkStorage/projects/glowsquid/.gitignore": "602c3e7127a95bcb5b684174f15a05d77d106e921f5c190ba4783815c9245a8d",
        "nx.json": "756cca89a4a8aa556ec9e519dc750cba747c908de98ac48e66fe4e4f7f105b1f"
      }
    },
    "params": "",
    "endTime": "2022-02-18T09:47:12.904Z",
    "status": 1,
    "cacheStatus": "cache-miss",
    "terminalOutput": "\u001b[2m> cargo +nightly..."
  }
]

   See Nx Cloud run details at https://nx.app/runs/yOkgEJjMBFF


glowsquid
```

**Comment by dannymcgee** [comment] 2022-05-25 02:42
Thanks for the report @Suyashtnt, unfortunately this will take a bit of research and debugging to fix, which I haven't had the time for yet, and I can't make any promises on when I'll be able to get to it.

**Comment by Suyashtnt** [comment] 2022-05-25 05:37
> Thanks for the report @Suyashtnt, unfortunately this will take a bit of research and debugging to fix, which I haven't had the time for yet, and I can't make any promises on when I'll be able to get to it.

I no longer use NX, but for the people who do just take your time :)

**Comment by IgnisDa** [comment] 2022-07-30 06:15
@dannymcgee I would like to contribute a fix for this. I have isolated the problem. Would you be willing to accept a pull request?

**Comment by IgnisDa** [comment] 2022-07-30 09:50
@dannymcgee I made a PR fixing this.

**Comment by dannymcgee** [comment] 2022-07-30 20:11
@IgnisDa Thank you so much! I'll try to get this merged in today.

**Comment by robi-wan** [comment] 2023-01-12 13:14
We are currently also running into this issue.
Liked mentioned in https://github.com/nxrs/cargo/pull/21 the issue is that ` the output of cargo metadata is too large, it overflowed the buffer`.

A minimal viable patch which works locally is taking this [line](https://github.com/nxrs/cargo/pull/21/files#diff-2705acd35f89e33ab805bb3f457587e4793b0afcc793bcb04692b2823731c848R37) `		maxBuffer: 50 * 1024 * 1024,`
and adding it to the `execSync` call:
```javascript
    let metadata = cp.execSync("cargo metadata --format-version=1", {
        encoding: "utf8",
        maxBuffer: 50 * 1024 * 1024,
    });
```

Another approach would be the usage of `child_process.spawn`.
See https://stackoverflow.com/a/68958420

**Comment by IgnisDa** [comment] 2023-01-12 13:19
@robi-wan I forked this repo and published the correct fix here: https://github.com/IgnisDa/npm-libs/tree/main/packages/nx-rust.

The solution you have posted will work but only for metadata below 50mb. For big projects, it would be more than that. It needs to be implemented using json streaming.

**Comment by robi-wan** [comment] 2023-01-12 14:42
@IgnisDa Thank you for this info - a possible workaround for us would be to use your fork with that fix.

My understanding of Nodejs code is not very good but regarding my understanding the root cause for this issue is the limited buffer used in `child_process.execSync`: the default buffer size for stdout is `1024 * 1024` (see https://github.com/nodejs/node/blob/91ca2d40419244a9c542be5ff162a837fcc3be82/lib/child_process.js#L95).
It even is the default when using `child_process.spawnSync` without changes in handling I/O to the spawned process.

(In your fix you also used  `child_process.execSync` with an extended buffer of 50 MB - so as I understand it your solution would also fail for big projects?)

You are right: streaming is the right approach but it should not just be used for JSON parsing. It should also be used for fetching the process output - I think therefore instead of `child_process.execSync` `child_process.spawnSync` should be used and something has to be done to redirect the stdout of `cargo metadata --format-version=1` into a resizable buffer or a stream.

**Comment by IgnisDa** [comment] 2023-01-12 15:26
@robi-wan Indeed I have increased the buffer size, but then later I have also parsed the json via streaming. You can see them here https://github.com/IgnisDa/npm-libs/blob/main/packages/nx-rust/src/graph/index.ts#L23-L37.

>  I think therefore instead of child_process.execSync child_process.spawnSync should be used and something has to be done to redirect the stdout of cargo metadata --format-version=1 into a resizable buffer or a stream.

I am not sure about this. I will try to test this theory once I have time.

**Closed** 2023-08-12 16:15 UTC
Labels: bug, help wanted
